version: "3.9"

services:
  app:
    tty: true
    restart: always
    image: go-fiber-mongodb:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - application
    depends_on:
      - mongodb
    command: ["go", "run", "main.go"]

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - application

networks:
  application:

volumes:
  mongodb:
